### ISSUE TITLE
Add ctz

### ISSUE THREAD

**Issue by michaeljclark** [cliffordwolf/xbitmanip#2]
It's a bit biased to exclude `ctz` without performing any quantitative analysis on the cost differential for efficient `ctz` i.e. macro-op fusion of `brev` and `clz` vs a first-class instruction. Noting that the cost of macro-op fusion is more costly for smaller implementations.

```
mclark@minty:~/src/sifive/riscv-qemu$ grep -r ctz . | wc -l
415
mclark@minty:~/src/sifive/riscv-qemu$ grep -r clz . | wc -l
516
```

Sure, `clz` is more popular than `ctz`:

- https://searchcode.com/?q=__builtin_ctz
- https://searchcode.com/?q=__builtin_clz

However if some performance critical code uses `ctz`, then single-issue in-order implementations are destined to have to execute two instructions.

This needs to be quantified. A quantitative analysis would not exclude `ctz` without having data.

Interestingly, openssl appears to only uses `ctz` in `./crypto/ec/curve448/curve448.c`. I can't find any references to `clz` in the repo.

supercop, the defacto crypto algorithm analysis benchmark suite looked after by DJB seems to use `clz` more than `ctz`. While `clz` is used for floating-point renormalization, it appears that `ctz` is popular in crypto algorithms.

```
mclark@monty:~/src/supercop-20160910$ grep -r builtin_ctz . | wc -l
     146
mclark@monty:~/src/supercop-20160910$ grep -r builtin_clz . | wc -l
      23
```

Linux seems to have more instances of `clz`

```
mclark@minty:~/src/sifive/riscv-linux$ grep -r __builtin_clz . | wc -l
93
mclark@minty:~/src/sifive/riscv-linux$ grep -r __builtin_ctz . | wc -l
20
```

Cifra - A collection of cryptographic primitives targeted at embedded use, seems to only use `ctz` and it is in the ocb critical path (`ocb_hash_block` and `ocb_encrypt_block`).

```
mclark@minty:~/src/sifive/cifra$ grep -r count_trailing_zeroes .
./src/bitops.h:static inline uint32_t count_trailing_zeroes(uint32_t x)
./src/ocb.c:  ocb_add_Ln(h->o, count_trailing_zeroes(h->i), h->offset);
./src/ocb.c:  ocb_add_Ln(o, count_trailing_zeroes(o->i), o->offset);
./src/ocb.c:  ocb_add_Ln(o, count_trailing_zeroes(o->i), o->offset);
```

We certainly need to do more analysis. i.e. benchmark and see the difference between having `ctz` take 1 or 2 retired instructions, otherwise we wouldn't be doing due diligence in the quantitative analysis.

If after actually performing quantitative analysis, we found that the difference is negligible, preferring `clz` over `ctz`, then we could make an _informed and quantitative_ decision on its inclusion or exclusion.

**Comment by cliffordwolf** [comment]
> https://searchcode.com/?q=__builtin_ctz
> https://searchcode.com/?q=__builtin_clz

Interesting.

There also seem to be a lot users of [__builtin_ffs](https://searchcode.com/?q=__builtin_ffs), which is just (ctz+1) & (xlen-1). But most of them are the pattern `ffs - 1`, which is equivalent to ctz for nonzero arguments (and looking at the code snippets, the arguments seem to be nonzero in most cases).

So if you add the number of `__builtin_ffs` to the number of `__builtin_ctz` then it looks like ctz and clz are being used at approximately the same frequency.

On the other hand, it seems like really nobody is using [__builtin_clrsb](https://searchcode.com/?q=__builtin_clrsb).  :)

> Noting that the cost of macro-op fusion is more costly for smaller implementations.

macro-op fusion comes in different flavors and, assuming a processor that already supports the C extension, fusing a sequence of two 16 bit instructions that do not spill any registers and produce a single output value into a single 32 bit instruction definitely is the cheapest form of macro-op fusion. I think in many cases the overhead is overrated.

But in case of `andc` we already decided that this operation is so frequent that it makes sense to dedicate a single 32 bit instruction to it, even though it could be fused from two 16 bit instructions.

The 32 bit encoding for unary functions is not that expensive. So I think in terms of encoding space it would make sense to trade the compressed CLZ instruction against two uncompressed opcodes: A CLZ and a CTZ.

Would that spec change be to your liking?

> benchmark and see the difference between having ctz take 1 or 2 retired instructions

my bet would be that it doesn't make any significant difference because neither ctz nor clz are frequent enough that one extra cycle makes a difference. (using the same frequency argument it was possibly overkill to include `c.blz` in the first place.)

> We certainly need to do more analysis. i.e. benchmark and see the difference [..] then we could make an informed and quantitative decision [..]

I absolutely agree.

**Comment by cliffordwolf** [comment]
I've tagged 0.34 and in that revision there is now `clz` and `ctz`.

**Comment by cliffordwolf** [comment]
To be honest, I think clz was originally included as primary method because someone was going through a list of x86 bit manipulation ISA extensions and saw that LZCNT was added in ABM and TZCNT was only added later in BMI1 (so LZCNT must be more important! :) but what that person possibly did not know is that both BSF and BSR are x86 instructions since the 80386, and xZCNT is only different from BSx in what CPU flags it sets..

Regarding your picture. I'd be worried about timing when putting all of that in a single cycle. I don't think it is necessary to chain GREV and CTZ/CLZ/PCNT just for bit reversal. If CTZ/CLZ/PCNT is it's own unit that that would be just one more xlen sized mux and the critical path would be much shorter.

**Comment by michaeljclark** [comment]
> On 21/04/2018, at 8:43 PM, Clifford Wolf <notifications@github.com> wrote:
> 
> To be honest, I think clz was originally included as primary method because someone was going through a list of x86 bit manipulation ISA extensions and saw that LZCNT was added in ABM and TZCNT was only added later in BMI1 (so LZCNT must be more important! :) but what that person possibly did not know is that both BSF and BSR are x86 instructions since the 80386, and xZCNT is only different from BSx in what CPU flags it sets..
> 
> Regarding your picture. I'd be worried about timing when putting all of that in a single cycle. I don't think it is necessary to chain GREV and CTZ/CLZ/PCNT just for bit reversal. If CTZ/CLZ/PCNT is it's own unit that that would be just one more xlen sized mux and the critical path would be much shorter.
> 

I understand.

However I’m curious what would be the most area efficient implementation, handing these functions, with critical path length as a secondary concern given the unit can be pipelined. i.e. Q. what is the most area efficient implementation, performance aside?

Of course there a quite a few potential implementations... I’m not proposing that implementation approach for a performance optimised implementation.
