### ISSUE TITLE
Does SLOI/SROI require 7-bit shamt field?

### ISSUE THREAD

**Issue by neelgala** [cliffordwolf/xbitmanip#4]
Hi,

In the current 0.36 draft on page 5  section 2.4

SROI and SLOI have the shamt field of 7 bits (i.e. [26:20] of the instruction). Is this a typo?
Wouldn't a value of shamt >63 simply be filling the entire rd with "all ones" which can be achieved by simply using the "not rd, x0" pseudo op of the base ISA.

Also if it does require 7 bits the following statement in the doc might not hold to be true:

"This means that a sloi instruction can be encoded similarly to an slli
instruction, but with a 1 in the highest bit of the encoded instruction."

**Comment by cliffordwolf** [comment]
Hi,

thanks for your interest in xbitmanip.

> SROI and SLOI have the shamt field of 7 bits (i.e. [26:20] of the instruction). Is this a typo?

No. It's the "RV128-ready" length of shamt. (Same for rotate shift.)

On RV32 shamt is [24:20] and on RV64 it is [25:20].

> "This means that a sloi instruction can be encoded similarly to an slli instruction.."

This is assuming that slli (and the other shift-immediate instructions) will use imm[26] for shamt[6] on RV128.

We will probably know very soon if this assumption turns out to be correct, as the RV128 work group is just starting its work right now. (Should they decide to use a different encoding for whatever reason then xbitmanip will be changed to reflect that other encoding scheme.)
